import type { FieldType } from '../ir.js';

/**
 * A line-oriented writer. Generators build text through this rather than concatenating
 * strings so indentation stays consistent and the output is byte-stable — the drift check
 * compares bytes, so any incidental variation would show up as a false failure.
 */
export class Writer {
  private readonly lines: string[] = [];
  private depth = 0;

  constructor(private readonly indentUnit = '    ') {}

  line(text = ''): this {
    this.lines.push(text === '' ? '' : this.indentUnit.repeat(this.depth) + text);
    return this;
  }

  lines_(texts: string[]): this {
    for (const text of texts) this.line(text);
    return this;
  }

  /** Emits `text` as a comment block, one prefixed line per source line. */
  comment(prefix: string, doc: string): this {
    for (const raw of doc.split('\n')) {
      this.line(raw === '' ? prefix.trimEnd() : `${prefix}${raw}`);
    }
    return this;
  }

  indent(body: () => void): this {
    this.depth += 1;
    body();
    this.depth -= 1;
    return this;
  }

  toString(): string {
    // Exactly one trailing newline, no trailing whitespace on any line.
    return this.lines.map((l) => l.replace(/\s+$/, '')).join('\n') + '\n';
  }
}

export function pascalCase(value: string): string {
  return value
    .split(/[_\-\s]+/)
    .filter(Boolean)
    .map((part) => part.charAt(0).toUpperCase() + part.slice(1))
    .join('');
}

export function snakeCase(value: string): string {
  return value
    .replace(/([a-z0-9])([A-Z])/g, '$1_$2')
    .replace(/[-\s]+/g, '_')
    .toLowerCase();
}

export function screamingSnakeCase(value: string): string {
  return snakeCase(value).toUpperCase();
}

/**
 * Banner for every generated file.
 *
 * Deliberately free of timestamps and machine names: the drift check compares generated
 * output byte for byte, and anything varying between runs would make it useless.
 */
export function banner(
  commentPrefix: string,
  sourceNote = 'packages/protocol/src/schemas',
): string[] {
  return [
    `${commentPrefix}Generated by @fiveprotect/protocol. Do not edit by hand.`,
    `${commentPrefix}`.trimEnd(),
    `${commentPrefix}Source of truth: ${sourceNote}`,
    `${commentPrefix}Regenerate with: npm run protocol:generate`,
    `${commentPrefix}CI fails when this file and the schemas disagree (npm run protocol:check).`,
  ];
}

/** True when a field may be absent from the wire payload. */
export function isOptional(type: FieldType): boolean {
  return type.kind === 'optional';
}

/** Strips one layer of `optional`, leaving every other type untouched. */
export function unwrapOptional(type: FieldType): FieldType {
  return type.kind === 'optional' ? type.inner : type;
}

/**
 * Human-readable note for constraints a target language cannot express in its type system.
 * Returns an empty string when there is nothing worth saying.
 */
export function constraintNote(type: FieldType): string {
  const inner = unwrapOptional(type);
  const parts: string[] = [];
  if (inner.kind === 'string') {
    if (inner.format) parts.push(`format: ${inner.format}`);
    if (inner.minLength !== undefined) parts.push(`min length: ${inner.minLength}`);
    if (inner.maxLength !== undefined) parts.push(`max length: ${inner.maxLength}`);
  } else if (inner.kind === 'int') {
    if (inner.min !== undefined) parts.push(`min: ${inner.min}`);
    if (inner.max !== undefined) parts.push(`max: ${inner.max}`);
  } else if (inner.kind === 'array' && inner.maxItems !== undefined) {
    parts.push(`max items: ${inner.maxItems}`);
  }
  return parts.length > 0 ? `(${parts.join(', ')})` : '';
}

/**
 * Writes a JSDoc block. A single-line doc is collapsed onto one line so short field docs
 * stay compact; anything longer keeps its paragraph structure.
 */
export function jsDoc(w: Writer, doc: string): void {
  const lines = doc.split('\n');
  if (lines.length === 1) {
    w.line(`/** ${lines[0]} */`);
    return;
  }
  w.line('/**');
  w.comment(' * ', doc);
  w.line(' */');
}

/** Thrown when a generator meets an IR construct it was never taught. */
export class UnsupportedTypeError extends Error {
  constructor(generator: string, type: FieldType) {
    super(
      `generator "${generator}" does not handle IR type "${type.kind}". ` +
        'Teach all four generators about it rather than working around it here.',
    );
    this.name = 'UnsupportedTypeError';
  }
}
