import js from '@eslint/js';
import globals from 'globals';
import tseslint from 'typescript-eslint';

export default tseslint.config(
  {
    ignores: [
      '**/dist/**',
      '**/build/**',
      '**/target/**',
      '**/node_modules/**',
      '**/coverage/**',
      // Generated by @fiveprotect/protocol. Style is the generator's business; correctness is
      // covered by the contract tests and the drift check.
      'packages/protocol/generated/**',
    ],
  },

  js.configs.recommended,
  ...tseslint.configs.recommendedTypeChecked,

  {
    languageOptions: {
      parserOptions: {
        projectService: true,
        tsconfigRootDir: import.meta.dirname,
      },
      globals: { ...globals.node },
    },
    rules: {
      // Errors that cross a process boundary are strings on the wire, and `unknown` in a
      // catch clause is the honest type for something a remote peer produced.
      '@typescript-eslint/no-unsafe-assignment': 'off',
      '@typescript-eslint/restrict-template-expressions': [
        'error',
        { allowNumber: true, allowBoolean: true },
      ],
      '@typescript-eslint/consistent-type-imports': [
        'error',
        { prefer: 'type-imports', fixStyle: 'inline-type-imports' },
      ],
      '@typescript-eslint/no-unused-vars': [
        'error',
        { argsIgnorePattern: '^_', varsIgnorePattern: '^_' },
      ],
      'no-console': ['error', { allow: ['warn', 'error'] }],
      eqeqeq: ['error', 'always', { null: 'ignore' }],
    },
  },

  {
    // Test files reach into internals on purpose and assert on values the type system has
    // already lost track of.
    files: ['**/*.test.ts', '**/test/**/*.ts'],
    rules: {
      '@typescript-eslint/no-unsafe-member-access': 'off',
      '@typescript-eslint/no-unsafe-call': 'off',
      '@typescript-eslint/no-non-null-assertion': 'off',
    },
  },

  {
    files: ['**/*.js', '**/*.mjs'],
    ...tseslint.configs.disableTypeChecked,
  },

  {
    // Browser code: the NUI frame runs inside CEF and the companion window inside the
    // Tauri webview. Neither is Node, so the environment is scoped to them rather than
    // enabled globally — a stray `document` in backend code should still be an error.
    files: ['resources/*/nui/**/*.js', 'apps/companion/ui/**/*.js'],
    ignores: ['apps/companion/ui/vitest.config.js'],
    languageOptions: {
      globals: { ...globals.browser },
    },
  },
);
